fix: Resolve symlinks for /dev/disk/by-partlabel
mendersoftware/mender pull request #1037
Opened 2022-09-10 13:59 UTC by Michaelhobo

We started labelling our partitions to solve disk naming issues when swapping disks between disk slots. However, when we pass /dev/disk/by-partlabel/root2 and /dev/disk/by-partlabel/root3 to Mender, we can't update because Mender throws an error: Active root partition matches neither RootfsPartA nor RootfsPartB.

Resolve by-partlabel as well to solve this problem.

Changelog: Resolve symlinks for /dev/disk/by-partlabel
Ticket: None

2022-09-12 07:26 UTC, kacf approved these changes
Thanks, looks good to me!

2022-09-12 07:28 UTC, kacf requested changes
Actually the CI is complaining about a couple of things: Can you make sure that:

* The copyright year at the top is updated.
* The code is formatted using `go fmt installer/partitions.go`.

2022-09-12 08:46 UTC, lluiscampos commented on installer/partitions.go
>  	// Only resolve /dev/disk/by-partuuid/ and /dev/root
Would be nice to update this comment too.

2022-09-12 15:27 UTC, Michaelhobo commented
> Thanks, looks good to me!

2022-09-12 15:27 UTC, closed without merging

2022-09-12 15:28 UTC, Michaelhobo commented
> Actually the CI is complaining about a couple of things: Can you make sure that:
> 
> * The copyright year at the top is updated.
> * The code is formatted using `go fmt installer/partitions.go`.

Done

2022-09-13 06:21 UTC, kacf approved these changes
Thanks!

2022-09-13 14:13 UTC, Michaelhobo commented
It seems like something is still failing, but I don't have access to see what it is?

2022-09-13 14:30 UTC, kacf commented
Yes, it's part of our internal CI. I'm pretty sure it's unrelated to your change, but I'll make a final check tomorrow.

2022-09-14 11:40 UTC, kacf commented
Yep, unrelated. Our internal CI is helpful but not perfectly stable.

2022-09-15 08:30 UTC, lluiscampos commented
@mender-test-bot cherry-pick to:
* 3.3.x