MEN-6121: Switch to CMake
mendersoftware/mender pull request #1105
Opened 2022-12-19 15:15 UTC by vpodzime

### Description

Switches the project from Autotools to CMake and introduces a dependency on LMDB (and C++ bindings for it) to see how things work with CMake.

2022-12-19 15:16 UTC, vpodzime commented
@mender-test-bot start pipeline

2022-12-19 15:36 UTC, vpodzime commented
[`test-docker`](https://gitlab.com/Northern.tech/Mender/mender/-/jobs/3496833867) fails because I had to switch the container to Ubuntu 22.04 because of the LMDB C++ bindings and C++ 17 required and the repo manipulation fails

2022-12-20 08:07 UTC, oleorhagen requested changes
Nice!

2022-12-20 08:08 UTC, oleorhagen approved these changes

2022-12-20 08:35 UTC, vpodzime commented on .gitignore
>  /common/json/impl/boost/libjson_la-boost_json.lo
Yeah, you forgot to remove it and change those names :stuck_out_tongue:

2022-12-20 08:37 UTC, vpodzime commented on tests/Dockerfile.daemon
>  RUN make
Not a difference here, but I run `cmake . && make` on my machine because `make` is an alias to `make -j -l10`.

2022-12-20 14:55 UTC, vpodzime commented
I guess it should be noted here that CMake might require some extra work from us (compared to Autotools) when doing [system introspection](https://cmake.org/cmake/help/latest/guide/tutorial/Adding%20System%20Introspection.html) (Autotools handle this automatically/implicitly).

2022-12-20 15:14 UTC, vpodzime commented
> ** ci/gitlab ** — Pipeline failed on Gitlab

Don't know how to fix or even debug this:
```
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Reading package lists...
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
...
```
Works just fine locally (and so does for @oleorhagen).

2022-12-21 09:37 UTC, vpodzime commented
> Don't know how to fix or even debug this:

Solved by not requiring Ubuntu 22.04

2022-12-21 10:34 UTC, oleorhagen approved these changes
Nice!

2022-12-21 12:15 UTC, merged