Update module file tree
mendersoftware/mender pull request #1210
Opened 2023-04-06 13:09 UTC by vpodzime

Ticket: MEN-6315

### TODO
- [ ] prepare files based on Artifact header data when #1203 is merged
- [ ] extend the test for the above data
- [ ] test for `DeleteFileTree()`
- [ ] add a piece of code/function to determine the path for the file tree

2023-04-11 09:03 UTC, kacf requested changes
You've used `close()` in a lot of places (I pointed out some, but not all). However, it's safer to rely on destruction semantics to do the job for us, and I think we should avoid using `close()` whenever possible, for several reasons:

* To casual code readers we should not make it appear as though `close()` is something that should be called. If so, usually only in destructors.
* Any place where we do call `close()` should be viewed with suspicion. This might be an indication that ownership and destruction semantics are not properly implemented (unlikely for `fstream`, but I'm thinking of the policy of using `close` in general, on any object). Removing all `close` calls that are unnecessary makes it easier to evaluate locations where it's used. Because there are, after all, *some* cases where it's appropriate.
* When hunting for resource leaks, it is much easier to trigger wrongly implemented destruction when `close()` isn't called anywhere. This immediately reveals the problem, and it can be fixed once, in the destructor. OTOH, if we close everywhere, and the destructor is not correctly implemented, we might miss resource leaks because it doesn't trigger on the main code path, only on an uncommon error, for example.

2023-04-12 09:09 UTC, vpodzime commented on common/io.cpp
> +error::Error WriteStringIntoOfstream(ofstream &os, const string &data) {
Right. But also `<<` is potentially/generally a lot more than just `write()`.

2023-04-12 09:10 UTC, vpodzime commented on mender-update/context/context.cpp
> +		return "Unknown";
Good point!

2023-04-12 09:11 UTC, vpodzime commented on common/io.cpp
> +			"Failed to open '" + path + "' for reading: " + strerror(io_errno))));
Yeah, I keep forgetting about this because I think about `err.message` which is then incomplete.

2023-04-12 09:12 UTC, vpodzime commented on mender-update/update_module/v3/platform/boost_filesystem/fs_operations.cpp
> +			"Failed to create directory '" + header_subdir_path.string() + "': " + e.what());
Exactly, I don't know what exactly Boost::fs puts in there and don't want to study it.

2023-04-13 06:29 UTC, kacf commented
> > You've used `close()` in a lot of places (I pointed out some, but not all). However, it's safer to rely on destruction semantics to do the job for us, and I think we should avoid using `close()` whenever possible, for several reasons:
> 
> Yup, agreed. Just an old habit from C. angel There are some cases where it is necessary, though. I was quite surprised that if you do `ifstream is; is.open(something); is.open(something_else)` the second `open()` does nothing, apparently. So an intermediate `close()` it is.

That is surprising! A justified use, indeed.

2023-04-13 06:30 UTC, kacf commented on common/io.cpp
> +error::Error WriteStringIntoOfstream(ofstream &os, const string &data) {
Yep! Not disagreeing with the approach, just making sure I understand it.

2023-04-13 06:41 UTC, kacf reviewed
Looks good to me now! I guess you still have some more work to do before approving though.

2023-04-19 09:53 UTC, oleorhagen commented
follow-up: https://github.com/mendersoftware/mender/pull/1222

2023-04-19 09:53 UTC, closed without merging