feat: changed parsing of some passthrough args in generators
mendersoftware/mender pull request #1605
Opened 2024-03-19 16:11 UTC by danielskinstad

Changelog: Returns an error when passing type, or when passing metadata to docker-artifact gen, and overrides output path
and name when passed as passthrough argument.

Ticket: MEN-7110

2024-03-22 13:37 UTC, lluiscampos requested changes
Nicely done! See comments below.

In addition, may I ask you (in a separate commit) to modify all the generators to be compatible with `sh`? :pray:  This makes sense as the generators are meant to be used for example from CI, where in many thin containers you don't have bash.

Also, this is not a feature in my opinion. Either a fix or a chore. I vote for fix.

2024-03-22 13:37 UTC, lluiscampos commented on support/modules-artifact-gen/single-file-artifact-gen
> +#!/bin/bash
(I know this is pre-existing, as the rest of the scripts were already using `bash`)

When possible, we should limit ourselves to `sh` syntax which is more portable. See below for an alternative command for `<<<`

2024-03-22 13:37 UTC, lluiscampos commented on support/modules-artifact-gen/single-file-artifact-gen
> +parse=$(xargs -n 2 printf "%s %s\n" <<< $passthrough_args)
An `sh` compatible alternative is
```suggestion
parse=$(echo $passthrough_args | xargs -n 2 printf "%s %s\n")
```

And similar for the next line.

Or, both combined:
```suggestion
echo $passthrough_args | xargs -n 2 printf "%s %s\n" | while read -r flag arg; do
```

2024-03-22 13:37 UTC, lluiscampos commented on support/modules-artifact-gen/single-file-artifact-gen
> +      ;;
Indentation here is off

2024-03-22 13:37 UTC, lluiscampos commented on support/modules-artifact-gen/single-file-artifact-gen
> +      echo "Error: Conflicting flag '$flag'. Already specified by the script."
The point is not that it is already specified (after others like `-o` are also specified), the point is that it is reserved for the script to use (iow it is the script who _decides_ the payload type)

2024-04-05 07:42 UTC, lluiscampos requested changes
Looking good!

:point_right:  One fix missing wrt migration to `sh`
:point_right:  One suggestion for improving

And,

> Also, this is not a feature in my opinion. Either a fix or a chore. I vote for fix.

I didn't mean to remove the changelog entries, only the category of the commit. I think that both commits are good changes to be ported to release branches and hence they should be either fix or chore and with a user friendly changelog.

2024-04-05 07:42 UTC, lluiscampos commented on support/modules-artifact-gen/directory-artifact-gen
> +#!/bin/sh
Another thing to pay attention when migrating from `bash` to `sh` is the if statements: `==` is bash syntax, `=` is sh syntax. I am getting the following error:
```
$ ./directory-artifact-gen -n hola -t hola --dest-dir /hola /home/lluis/Documents/ -- -T something
./directory-artifact-gen: 150: [: /hola: unexpected operator
Error: Conflicting flag '-T'. Already specified by the script.
```

2024-04-05 07:42 UTC, lluiscampos commented on support/modules-artifact-gen/directory-artifact-gen
> +)
Good catch with the subshell. I didn't see this coming! :exploding_head: 

To make it more obvious I recommend 1) adding a good comment on why we need the subshell (to be able to override the variables then passed to `mender-artifact` commands) and 2) moving the `rm` commands out of the subshell, as these variables are not being overridden.

2024-04-08 06:48 UTC, lluiscampos approved these changes

2024-04-08 07:34 UTC, danielskinstad commented
@mender-test-bot start pipeline

2024-04-08 09:42 UTC, merged

2025-04-02 07:47 UTC, MichaelSteurer commented on support/modules-artifact-gen/directory-artifact-gen
> +echo -n $passthrough_args | xargs -n 2 printf "%s %s\n" | (while read -r flag arg; do
Not sure if this is the right place to put, @danielskinstad: On MacOS this fails on the command line because it outputs the '-n' and hence breaks the parser in the loop:

`$ /bin/sh -c "echo -n 123"`
prints `-n 123\n` instead of `123`

See [this thread on SO](https://stackoverflow.com/questions/64771044/why-does-echo-n-command-not-work-in-a-sh-script).