artifact-gen: Improve error message when mender-artifact is not found.
mendersoftware/mender pull request #629
Opened 2020-10-16 08:51 UTC by kacf

Fixes MEN-4044.

Changelog: Title

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

2020-10-17 16:01 UTC, lluiscampos requested changes
See my comment below. I think we need to rework a bit.

2020-10-17 16:01 UTC, lluiscampos commented on support/modules-artifact-gen/docker-artifact-gen
>  check_dependency jq
If we change this, please let's make it consistent across the three scripts.

2020-10-19 05:35 UTC, kacf commented on support/modules-artifact-gen/docker-artifact-gen
>  check_dependency jq
`set -e` is enabled, so it exits correctly on all three checks.

I think your suggested fix is indeed a bit overkill as then the message has to be repeated three times. I think the current approach is kind of Go-like, in the sense that the innermost function logs, then returns, and then the outer function may, or may not, log additional information.

2020-10-19 07:26 UTC, lluiscampos approved these changes
Ok. Makes sense.

2020-10-19 07:42 UTC, kacf commented
Thanks!

2020-10-19 07:43 UTC, merged