MEN-4534: Add UpdateControlMapExpirationTimeSeconds to mender.conf
mendersoftware/mender pull request #737
Opened 2021-04-08 10:56 UTC by oleorhagen

See: https://tracker.mender.io/browse/MEN-4534 for info

2021-04-12 06:37 UTC, kacf requested changes
One structural change is needed, but looks good otherwise.

2021-04-12 06:37 UTC, kacf commented on conf/config.go
> +	UpdateControlMapExpirationTimeSeconds int
It should be outside the `DBusConfig` structure. It is not DBus specific, DBus is just one of the ways that it can be updated.

2021-04-12 12:35 UTC, oleorhagen commented
@mender-test-bot start pipeline

2021-04-13 08:51 UTC, kacf approved these changes
One wrong log message below, looks good otherwise!

2021-04-13 08:51 UTC, kacf commented on conf/config.go
> +		log.Info("'DBus.UpdateControlMapExpirationTimeSeconds' is not set " +
~DBus.~

2021-04-13 12:55 UTC, oleorhagen commented
@mender-test-bot start pipeline :pray:

2021-04-14 06:25 UTC, merged