MEN-4548: Implement the Query update logic
mendersoftware/mender pull request #755
Opened 2021-05-05 08:05 UTC by oleorhagen

This is based on top of 4547, which may be due to change according to review, but the implementation itself should be pretty freestanding.

2021-05-05 11:28 UTC, kacf requested changes

2021-05-05 11:32 UTC, oleorhagen commented on app/updatemanager.go
> +				return
Good catch, I just found this myself (I'm using this functionality in `MEN-4547` now too)
Solved it with a `goto`

2021-05-05 11:34 UTC, oleorhagen commented on app/updatemanager.go
> +		return maps[i].Priority < maps[j].Priority
Yes, will do. I really wasn't sure about what should be deemed the higher priority, like in `Unix` it is usually the other way around right. `19` is really _nice_ :), not `-20`

2021-05-05 11:34 UTC, oleorhagen commented on app/updatemanager.go
> +		return maps[i].Priority < maps[j].Priority
A lot of testcases will then need an inversion too :p

2021-05-06 09:23 UTC, oleorhagen commented on app/updatemanager.go
> +		log.Errorf("Some foobar descriptive error message, cause this should not happen!")
I'm even tempted to use a panic here...

2021-05-06 09:32 UTC, oleorhagen commented on app/updatemanager_test.go
> +	t.Run("Fail exists: Action", func(t *testing.T) {
All these could probably be written into a nice table test, if you find them hard to decipher

2021-05-06 09:32 UTC, oleorhagen commented on app/updatemanager.go
> +func queryActionList(stateActions []string) string {
Not the best name, I just got `query` stuck in my head

2021-05-06 09:33 UTC, oleorhagen commented on app/updatemanager.go
> +		return maps[i].Priority > maps[j].Priority
Reversed the priorities, as mentioned

2021-05-06 11:05 UTC, kacf commented on app/updatemanager.go
> +		return maps[i].Priority < maps[j].Priority
Hehe, yes, I also thought about that, but they call it "nice value", not priority, so it doesn't really apply. I don't have a very strong preference, but intuitively, in an API it seems natural that a higher number would mean higher priority.

2021-05-06 11:06 UTC, kacf commented on app/updatemanager.go
> +		return maps[i].Priority > maps[j].Priority
:+1:

2021-05-06 11:06 UTC, kacf approved these changes

2021-05-06 11:15 UTC, oleorhagen commented
Waiting for https://github.com/mendersoftware/mender/pull/748 to be merged before continuing

2021-05-10 10:29 UTC, oleorhagen commented
Pipe passed previously on the rerun. Only fixed an error log message. Going to merge without rerunning.

2021-05-10 12:31 UTC, merged