Add artifact_name to device provides if not found in store
mendersoftware/mender pull request #834
Opened 2021-07-16 09:25 UTC by prashanthjbabu

Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>
Changelog: Commit

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

This PR fixes a corner case for delta updates. 
Consider a fresh device which has no device provides . 
Now when we ask for an update(`deployment/next` API) , we provide `artifact_name` as device provides by getting it from `GetCurrentArtifactName`
Now once the client gets the artifact from the server and when it comes to installing the artifact , the device calls `maybeVerifyArtifactDependsAndProvides` to ensure that the `depends` of the artifact matches with the `provides` of the device .
In such a case for a fresh device which has `no provides` in the datastore , the `LoadProvides` function does not have `artifact_name` in it causing the artifact install to fail since it wouldnt match with the `artifact_name` depends of the artifact.
To take care of this , we need to ensure that if the datastore does not return `artifact_name` we take it from `GetCurrentArtifactName`( which ensures it takes it from the artifact_info file if not present in the store.)

This issue is not seen if the first deployment is not a delta deployment since after the first deployment , the mender client stores the `artifact_name` in provides section of data store.

2021-07-19 06:15 UTC, prashanthjbabu commented
@lluiscampos can you please take a look at this

2021-07-19 07:49 UTC, kacf commented
While I'm not against this fix, I have to ask: Does it actually solve the problem? Delta artifacts depend on checksums, and this will not be improved by this PR.

For your information, we have a much more substantial and complete fix planned for this [here](https://tracker.mender.io/browse/MEN-2582), which will also solve the checksum problem, as well as the artifact name problem which you fixed. I'm not sure exactly when this will be implemented, but I believe the third or fourth quarter this year.

2021-07-19 08:23 UTC, prashanthjbabu commented
@kacf thanks for your response . This is only for consistency reasons , since we are using the `artifact_info` fallback mechanism while asking the server for an update , the same should be maintained while validating the `provides`/`depends`  incase there is an artifact which has `artifact_name` as a key in its `depends`. 

Considering the long timeline , I feel it would be good if we can get this in till  the complete fix is in.

2021-07-20 12:09 UTC, kacf requested changes
Ok, that's reasonable. I also talked to our product manager, and it's unlikely that [MEN-2582](https://tracker.mender.io/browse/MEN-2582) will make it into 3.1, our next release. So then it makes sense to include this as a partial solution in the meantime.

Content wise, this looks good, but our code checker is complaining about cyclomatic complexity. We use it to keep functions to a reasonable length. Your two sections do pretty much the same thing, so maybe you can move the logic into its own function (perhaps in `mender.go`?) and then call it from both places. That should be enough to make it happy, I think.

2021-07-22 05:09 UTC, prashanthjbabu commented
@kacf Thanks for taking a look at this . I've made the necessary changes .

2021-07-22 12:12 UTC, kacf approved these changes
Thanks! I rebased to code to fix some unrelated test errors.

2021-07-23 11:10 UTC, kacf commented
There is an error in one of the unit tests. I think I know why, but I won't have time to look at it today, and I'll be gone for a bit. I'll try to pick this up the week after next week. Given that there will not be any releases for some time, it's not that urgent anyway.

2021-08-04 05:48 UTC, prashanthjbabu commented
@kacf friendly ping :)

2021-08-04 08:23 UTC, kacf commented
Hehe, thanks. I found the issue, just a one liner. Will retest now.

2021-08-06 06:09 UTC, merged

2021-08-06 06:14 UTC, kacf commented
Thanks! Cherry-picked to 3.0.x and 2.5.x as well. 2.6.x won't get any more releases.