log: add missing space when joining lines
mendersoftware/mender pull request #959
Opened 2022-03-15 14:40 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2022-03-15 14:41 UTC, oleorhagen commented
@lluiscampos if ur happy, plz merge

2022-03-16 07:24 UTC, lluiscampos requested changes

2022-03-16 07:24 UTC, lluiscampos commented on device/device.go
>  	logMsg := "Returning artifact name from %s file." +
Missing space here to after the `.`

2022-03-16 07:34 UTC, lluiscampos approved these changes

2022-03-16 08:00 UTC, oleorhagen commented
Merge too plz @lluiscampos  :pray:

2022-03-16 09:27 UTC, merged